config/routes.rb
Rails.application.routes.draw do
  root :to => 'static#index'

  resources :posts
  resources :tags
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags

  validates :title, :presence => true
  validates :content, :presence => true

  default_scope {order('updated_at DESC')}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  validates :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @tags = Tag.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    @tags = @post.tags
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      @tags = @post.tags
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :tag_ids => [])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @posts = Post.all
    @tags = Tag.all
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to tags_path
    else
      render :new
    end
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tag_path(@tag)
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix the following errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
  <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render 'layouts/errors', :object => @post %>

<%= form_for @post do |f| %>
  <p><%= f.label :title %>
  <%= f.text_field :title %></p>
  <p><%= f.label :content %>
  <%= f.text_area :content %></p>

  <h4>Add Tags:</h4>
    <ul>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :description) do |b| %>
      <li><%= b.label { b.check_box } %>
      <%= b.object.description %></li>
    <% end %>
    </ul>

  <%= f.submit %>
<% end %>

app/views/posts/_listing.html.erb
<% if @posts.any? %>
  <h1>Posts:</h1>
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to post.title, post_path(post) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no posts yet.</p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'listing' %>

<p><%= link_to "New Post", new_post_path %></p>

<hr>
<%= link_to "Back to Homepage", root_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<p><%= link_to "Edit Post", edit_post_path(@post) %></p>
<p><%= link_to "Delete Post", post_path(@post), :data => {:confirm => "Are you sure you want to delete this post?", :method => "delete"} %></p>

<% if @post.tags.any? %>
  <h5>Tags for this post:</h5>

  <ul>
    <% @post.tags.each do |tag| %>
      <li><%= link_to tag.description, tag_path(tag) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no tags yet!</p>
<% end %>

<p><%= link_to "Return to Posts", posts_path %></p>

app/views/tags/_form.html.erb
<%= render('layouts/errors', :object => @tag) %>

<%= form_for @tag do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <p><%= f.submit %></p>
<% end %>

app/views/tags/_listing.html.erb
<% if @tags.any? %>
  <h1>Tags:</h1>
  <ul>
    <% @tags.each do |tag| %>
      <li><%= link_to tag.description, tag_path(tag) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no tags yet.</p>
<% end %>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= render 'form' %>

app/views/tags/index.html.erb
<%= render 'listing' %>

<p><%= link_to "New Tag", new_tag_path %></p>

<hr>
<%= link_to "Back to Homepage", root_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

app/views/tags/show.html.erb
<h1>Posts with the tag "<%= @tag.description %>"</h1>

<% @tag.posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
<% end %>

<p><%= link_to "Edit Tag", edit_tag_path(@tag) %></p>
<p><%= link_to "Delete tag", tag_path(@tag), :data => {:confirm => "Are you sure you want to delete this tag?", :method => "delete"} %></p>

<hr>

<%= link_to "Back to Homepage", posts_path %>